[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors.bright]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.primary]
background = "0x282828"
foreground = "0xd4be98"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[cursor]
blink_interval = 750
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[terminal]

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.85
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 10
y = 10

[keyboard]
